---
title: "Macro ML"
author: "Jean-Galaad BARRIERE"
date: "05/11/2022"
output: pdf_document
---

```{r}
#########   Librairies
library(dplyr)

##############
file <- "data/2020-11.csv"
#file <- "C:\\Users\\jean-\\OneDrive - Ecole Polytechnique\\4A ENSAE\\cours\\Macroeconometry and ML\\2020-11.csv"

data0 <- read.csv(file = file)



#On ne garde que les données d'après 1960 # non car calcul de différence
x <- data0$sasdate
data1 <- data0[(x!="Transform:" & nchar(x)>2),]
y<-data1[,1]

varnames <- data.frame("FRED_ticker"=colnames(data1)[-1])
write.csv(varnames, "varnames.csv", row.names = F)


##### Sur ces données, on enlève les séries inutiles
# on importe le csv avec les idnications sur les variables
df <- read.csv("data/variables.csv",sep=";")
df <- filter(df,Inclusion==1)
var <- df$FRED_ticker

#on garde la date
var <- c("sasdate", var)


data <- data1[var]
data


```

```{r}
### Transformations des séries
var_names <- colnames(data)
for(i in 2:length(var_names)){ #on exclut la 1ère col (date)
  variable <- var_names[[i]]
  transfo <- df$Transformation[df$FRED_ticker==variable]
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
  print(transfo)
>>>>>>> d4fe02aa383892543b502d80ae6641b8b18f9ba1
>>>>>>> a4883932ae1f72526fc23e296087f68eae4b0f29
  if(!is.null(transfo)){
    if(transfo=="Log"){
      data[,i]<-log(data[,i])
    }
    if(transfo=="Difference"){
      data[,i]<-c(NA, diff(data[,i])) #une case de moins si on prend la diff
    }
    if(transfo=="Log growth"){
      tmp <- data[,i]
      tmp <- tmp/lag(tmp)
      tmp<-log(tmp)
      data[,i]<-c(tmp) #une case de moins si on prend la diff
    }
  }
}

## Intervalle temporel
data$sasdate<-as.Date(data$sasdate, format = "%m/%d/%Y") # conversion en date
data <- filter(data, sasdate>="1960-01-01" & sasdate<"2020-01-01")

### Enregistrement des données
saveRDS(data, "data/FRED_data.rds")
```

## PCA

```{r}
library(FactoMineR)

data <- readRDS("data/FRED_data.rds")
data0 <- select(data, -1) # on enlève la date
<<<<<<< HEAD
#data0[is.na(data0)]<-1 # à voir comment on les traite
=======
<<<<<<< HEAD
#data0[is.na(data0)]<-1 # à voir comment on les traite
=======
data0[is.na(data0)]<-1 # à voir comment on les traite
>>>>>>> d4fe02aa383892543b502d80ae6641b8b18f9ba1
>>>>>>> a4883932ae1f72526fc23e296087f68eae4b0f29
sum(is.na(data0))

pca <- PCA(data0, ncp=9)
View(pca$var$coord)
summary(pca)
```

<<<<<<< HEAD


=======
<<<<<<< HEAD


## Sparse PCA

Essayons avec le même package que les auteurs :

J'ai ajusté à la main le paramètre sumabsv pour me rapproche des 108 nonzero weights.

On a un résultat qui ressemble fortement à celui de l'article!

```{r}
library(PMA)
spca <- SPC(data0,sumabsv = 3, K=9)
View(spca$v)
weights <- spca$v
row.names(weights)<- colnames(data0)
sum(weights!=0)
=======
>>>>>>> a4883932ae1f72526fc23e296087f68eae4b0f29
## Sparse PCA

Essayons avec le même package que les auteurs :

J'ai ajusté à la main le paramètre sumabsv pour me rapproche des 108 nonzero weights.

On a un résultat qui ressemble fortement à celui de l'article!

```{r}
<<<<<<< HEAD
library(PMA)
spca <- SPC(data0,sumabsv = 3, K=9)
View(spca$v)
weights <- spca$v
row.names(weights)<- colnames(data0)
sum(weights!=0)
=======
library(sparsepca)
spca <- robspca(data0, k=9)
View(spca$loadings)
>>>>>>> d4fe02aa383892543b502d80ae6641b8b18f9ba1
>>>>>>> a4883932ae1f72526fc23e296087f68eae4b0f29
```

